### ISSUE TITLE
Support lighting experience

### ISSUE THREAD

**Issue by jeffrey008** [kpeterson85/Salesforce-Quick-Login-Chrome-Extension#10]
Currently this extension does not support Lighting experience. Is it easy to make it work with LE? I am ready to contribute.

**Comment by kpeterson85** [comment]
@jeffrey008 I pushed out an update to the extension recently. Can you make sure you received it (should say version 2 now). If you have not yet you can go to the chrome extensions page (chrome://extensions/) and turn on the Developer option in the top right and then it will provide you an Update button you can click to try and force all extensions to update.

Once you have the latest version, Chrome should alert you that the extension is disabled until you accept its additional permissions (requesting access to lightning URLs). After that you should be able to click the extension while on lightning pages.

Please test logging in as people while on different lightning pages and confirm that it still keeps you on the same page when it logs you in as the other person.

Thank you!

**Comment by jeffrey008** [comment]
It works for me, thanks bro!
