### ISSUE TITLE
Installed but can't use

### ISSUE THREAD

**Issue by taracroberts33** [kpeterson85/Salesforce-Quick-Login-Chrome-Extension#11]
I installed from the Chrome store but can't get it to work. When I click the icon and Salesforce.com Quick Login as it takes me to back to the the Chrome store to download. I also followed the steps to download from source and still can't get it to work.

**Comment by kpeterson85** [comment]
It does not currently work in Lightning which could be the issue.  I will be releasing a new version soon that does.

**Comment by chrisbowers80** [comment]
@kpeterson85 any update on your Lightning-compatible version?

**Comment by sshouse** [comment]
@kpeterson85  also interested in the updated version for lightning - is this still on your roadmap?

**Comment by kpeterson85** [comment]
@taracroberts33 @chrisbowers80 @sshouse I pushed out an update to the extension last night.  Can you make sure you received it (should say version 2 now).  If you have not yet you can go to the chrome extensions page (chrome://extensions/) and turn on the Developer option in the top right and then it will provide you an Update button you can click to try and force all extensions to update.

Once you have the latest version, Chrome should alert you that the extension is disabled until you accept its additional permissions (requesting access to lightning URLs).  After that you should be able to click the extension while on lightning pages.

Please test logging in as people while on different lightning pages and confirm that it still keeps you on the same page when it logs you in as the other person.

Thank you!
