### ISSUE TITLE
Available in Lightning?

### ISSUE THREAD

**Issue by jmarnzen** [kpeterson85/Salesforce-Quick-Login-Chrome-Extension#12]
I love this tool so much! Will you be making it compatible with Lightning? Thanks.

**Comment by kpeterson85** [comment]
I pushed out an update to the extension recently. Can you make sure you received it (should say version 2 now). If you have not yet you can go to the chrome extensions page (chrome://extensions/) and turn on the Developer option in the top right and then it will provide you an Update button you can click to try and force all extensions to update.

Once you have the latest version, Chrome should alert you that the extension is disabled until you accept its additional permissions (requesting access to lightning URLs). After that you should be able to click the extension while on lightning pages.

Please test logging in as people while on different lightning pages and confirm that it still keeps you on the same page when it logs you in as the other person.

Thank you!

**Comment by jmarnzen** [comment]
Thanks, Kyle! I updated it but wasn't able to get it to load but I'll keep trying.
 
We implemented SSO for our Salesforce org, so I usually have to go incognito to login as another user anyway. (No extensions in incognito mode.)

Thanks for getting back to me and for making this great tool that hopefully will work well for others.
