### ISSUE TITLE
Include all users from list view in large orgs

### ISSUE THREAD

**Issue by kpeterson85** [kpeterson85/Salesforce-Quick-Login-Chrome-Extension#2]
Orgs with hundreds of users might only show a portion of the users listed in a list view .  Can all users be shown somehow?  Maybe make multiple requests for the list view's pages or force feed the number of rows querystring.

**Comment by kpeterson85** [comment]
When requesting the user listview page the extension already passes the querystring rowsperpage=1000.  Need to research if Salesforce even accepts this high of a number or how high it can go.

**Comment by mwelburn** [comment]
1000 seemed to be the max. I was considering a loop of requesting the next 1000 until you finish, but with communities/portal users that list could be hundreds of thousands of users (and thus hundreds of pages).

I think if you wanted to go this route you'd need to cache the response in some way so it at minimum isn't re-running the GET every time a new page is navigated to.

**Comment by kpeterson85** [comment]
Paging was added so users can click through pages of 1000 users at a time
