### ISSUE TITLE
Would love to buy it, but it won't let me change the associated google email address.

### ISSUE THREAD

**Issue by DeannaArcane** [kpeterson85/Salesforce-Quick-Login-Chrome-Extension#4]

**Comment by kpeterson85** [comment]
Hi Deanna, the extension is free to use and can be added to your Chrome browser by visiting the URL below and clicking the Add To Chrome button in the top right of the window.

https://chrome.google.com/webstore/detail/salesforcecom-quick-login/dccccilgophpadpomgajjlkkioipoojh

**Comment by DeannaArcane** [comment]
That's exactly what I did, and I wish to purchase it, but it defaults to an email for me (perhaps through Google?) that it displays at the top of the purchase page, which I can't seem to change. Ive logged out of that account, reopened the browser, etched, but I can't correct that email. 

--------
Deanna Simpson
Chief Technical Solutions Architect
Arcane Knowledge Corp
1-604-785-2026
Deanna@arcaneknowledge.ca

**Comment by kpeterson85** [comment]
Hi Deanna, Do you mind including a screenshot of the page you end up on?  I am not familiar with a purchase page coming up in the process.  Usually users click the Add button and it gets installed right then.

**Comment by DeannaArcane** [comment]
Hi Kyle,

I’ve already installed it and have been using it for a couple years — it’s great! Now, I’m trying to buy it, but it defaults to deanna.simpson@stratus360.com — which is an email account used for one of my client, not my primary address. I’m trying to figure out how to change it.  



---------------------
Deanna Simpson
Chief Technical Applications Architect
Arcane Knowledge Corp
604-785-2026

**Comment by kpeterson85** [comment]
Hi Deanna, can you please provide a link where you are trying to buy it from or a screenshot where you see a buy option.

**Comment by DeannaArcane** [comment]
Hi Kyle,

You click the Force.com Logins button on the address bar, and in the top right corner, there’s an Option button. You click that, and this page comes up:




Then you click the License tab, and the page I previously sent you comes up. In the top-right, there’s an associated email address, but even though I’ve logged out of that account and restarted my browser, I can’t get it to allow me to use my actual address.




---------------------
Deanna Simpson
Chief Technical Applications Architect
Arcane Knowledge Corp
604-785-2026

**Comment by kpeterson85** [comment]
Hi Deanna,

I believe you are looking for help with the Force.com Logins extension (https://chrome.google.com/webstore/detail/forcecom-logins/ldjbglicecgnpkpdhpbogkednmmbebec?hl=en)

This is the github for the Salesforce.com Quick Login As extension (https://chrome.google.com/webstore/detail/salesforcecom-quick-login/dccccilgophpadpomgajjlkkioipoojh)

You can find help for the Force.com Logins extension by clicking the support tab in the chrome store for the extension (the first link) or by visiting http://forcecomlogins.jimdo.com/.

I hope this clears up the confusion.

**Comment by DeannaArcane** [comment]
Hi — No, actually, I don’t understand how the download page will help me change the associated email address.
Can you provide step-by-step instructions as to how I can buy your product under the email address I actually use?

Thanks.
---------------------
Deanna Simpson

**Comment by kpeterson85** [comment]
I cannot help you with the Force.com Logins product, this github project you are in is a different product.  Please try contacting the Force.com Logins product people.  http://forcecomlogins.jimdo.com/contact/
